### ISSUE TITLE
Bay-Zombies - Prying Door & Damaging Synthetics + Mechs.

### ISSUE THREAD

**Issue by Yantarii** [UristMcStation/UristMcStation#1274]
### Describe the problem you're trying to solve

- Bay Zombies cannot pry doors, and cannot get past any non-general access doors, meaning they have to stay in hallways and other areas.

- Bay Zombies cannot damage Mechs at all, meaning they have no ability to counter Mechs & Borgs in a round.

- Bay Zombies cannot do anything towards Synthetic Crew, i.e the consume verb and such. Meaning they have to keep consistently attacking them until they are fully crit and dead.

### Describe the solution you'd like to see

Zombies should be able to pry open doors, allowing them access into areas with the disarm or grab intent. Additionally being able to destroy doors or smash them open would be a nice feature.

Zombies should be able to damage Mechs slowly in some way, so that 2-3 zombies working together can do some decent damage against them. Additonally being able to attack borgs would be very nice.

Having the consume verb work somewhat on downed synthetic crew, or for example just FBP would be nice, not fully damaging/killing them but damaging internal synth organs or something similar.

**Comment by scrdest** [comment]
Oddly, mechs are _supposed_ to take damage from zombies already.

The logic is, if the attacker is on HARM intent and there is a pilot inside the mech, the first check is if the hatch is open.

If the hatch is open, the attacker, regardless of species, will try to drag the pilot out.

Otherwise, if the attacker has MUTATION_FERAL (which zombies should have), the mech is attacked for 5 dmg.
