### ISSUE TITLE
Hunter rifle cannot hit anything while scoped

### ISSUE THREAD

**Issue by CaraS212** [UristMcStation/UristMcStation#1281]
### Feedback

Either through SkillIssue(TM) or bad luck the '/obj/item/gun/projectile/manualcycle/hunterrifle/scoped' cannot hit anything while scoped unless it is 1 tile or so off screen. This seems to be the case for the Anti material rifle as well.

Took a whole box of sniper ammo to kill a pirate from across the actors stage.

**Comment by ggermanicus** [comment]
[this line](https://github.com/ggermanicus/UristMcStation/blob/fd9c29f9d81d7a2f587b9b7e11b2780552a4a750/code/modules/projectiles/gun.dm#L346) is the culprit. i don't know how the pro coders link stuff.

this does work, it just means that often your accuracy mod is limited by how many seconds you've stood still instead of your accuracy.
stay still for an appropriate amount of time and you should see better results. the days of sniper meta are long gone.

unless we all hate this, then i'll change it

**Comment by scrdest** [comment]
> [this line](https://github.com/ggermanicus/UristMcStation/blob/fd9c29f9d81d7a2f587b9b7e11b2780552a4a750/code/modules/projectiles/gun.dm#L346) is the culprit. i don't know how the pro coders link stuff.
> 
> this does work, it just means that often your accuracy mod is limited by how many seconds you've stood still instead of your accuracy. stay still for an appropriate amount of time and you should see better results. the days of sniper meta are long gone.
> 
> unless we all hate this, then i'll change it
> 
> edit to add: the scoped rifle could definitely use a buff in scoped_accuracy though regardless, 6 ain't enough even when you _are_ standing still

Good find. We could just give it a _lot_ of accuracy; the way it works is that the lowest of accuracy and stillness is the upper bound on the Real Deal Accuracy, so high-acc weapons only get very good if you stay still for a long time.

For example, if we gave the rifle an accuracy = 60, someone staying still for 1 min would be almost guaranteed a hit.

**Comment by CPU-Blanc** [comment]
Addressed in #1309
