### ISSUE TITLE
Holodeck fire ends round

### ISSUE THREAD

**Issue by Skeeve2** [UristMcStation/UristMcStation#273]
Balance issue, holodeck fire will destroy entire station, killing everybody in literal minutes, causing mass pressure issues and force a shuttle call. 

Most likely needs to be disabled completely, or toned way way way down.

**Comment by Skeeve2** [comment]
Additional : ERT suits are not fireproof, so calling them is not advised.

**Comment by JacobLee1** [comment]
The holodeck has been there since the map was made for /tg/station's codebase. It was still dangerous then, but when we switched to Bay, ZAS started turning the holodeck into Hell made manifest. Fires melting walls made it more or less unstoppable... I've seen the issue for a long time, but could never see how to fix it beyond remapping large chunks of the map. I've seen the same thing happen with phoron fires in med/sci.

As with most fires, the best chance you have is to either fireproof yourself and RCD a floor in the room, or lock down the area and RCD the floor in the rooms it hasn't spread to yet, so it vents when it melts down the walls.

**Comment by Skeeve2** [comment]
The best choice is to basically disable it until we can get an atmos fix.

**Comment by Flip-Sandwich** [comment]
solved by #277 apparently

**Comment by Glloyd** [comment]
Tentatively fixed?
