### ISSUE TITLE
Rounds end when roundstart antagonists die.

### ISSUE THREAD

**Issue by Addle** [UristMcStation/UristMcStation#380]
If you spawn traitors in vampire and the vampires die, the game ends despite traitors still being alive. This happens for most gamemodes, but not malf which never ends for some reason.

**Comment by Vakothu** [comment]
I actually checked the code, Malf is specifically set to not end on antag death, it's a single variable.

**Comment by scrdest** [comment]
That's not a bug, that's a feature. Only the mode's 'core' antags are counted for end_on_antag_death. Admin-spawned and 'non-core' antags (IIRC on them, some modes have that kind of thing defined) spawn as normal in a mode, but aren't counted for death.

**Comment by Glloyd** [comment]
Still, it'd be nice to have a workaround so we can extend antag rounds if
we want. Like adding more vamps to vamp or adding tators to vamp.

On Fri, Mar 25, 2016 at 7:16 AM, scrdest <notifications@github.com> wrote:

> That's not a bug, that's a feature. Only the mode's 'core' antags are
> counted for end_on_antag_death. Admin-spawned and 'non-core' antags (IIRC
> on them, some modes have that kind of thing defined) spawn as normal in a
> mode, but aren't counted for death.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/380#issuecomment-201243644>
>



-- 
Graham Lloyd

**Comment by scrdest** [comment]
Adding more vamps to vamp will, AFAIK, work like that, since they are the 'core' antag of the gamemode; if I reenabled traitorvamp but kept end_on_ etc. then it would end when there's no more traitors AND vamps, and so on, roundstart or latespawned.

If you want to do that on runtime, you can, too. Add the antagonist type of your choosing to the mode's antag_tags (I believe you can do it via Game Panel) and it will be taken into consideration for that check. 

Finally, you could just disable end_on_antag_death for the gamemode entirely. The new antag system also supports enabling autotraitor-style behavior for any mode and combination of antags by changing a single var in the gamemode datum.

**Comment by scrdest** [comment]
Not strictly an issue; if you want to override it for adminfuckery, flip the var in gamemode datum.
