### ISSUE TITLE
Security: Brig/Armory hallway has no doors between prison cells and armory access

### ISSUE THREAD

**Issue by Psyentific** [UristMcStation/UristMcStation#458]
As it is now, I can walk out of a prison cell and walk right up to the Armory doors. If there's no power, I could even crowbar it open and help myself. In addition, there's only two doors standing between Maint and the Armory - That's less than a full RCD.

Proposed solution - Double doors at either of two marked points. The lower, blocks Interrogation Observation, AI Coresat, Armory and Warden and would need access restrictions set to one of those. The upper blocks only Armory, and would need access restrictions for Armory only.

![image](https://cloud.githubusercontent.com/assets/6664133/14939427/29f31824-0efb-11e6-8fbd-2efddec41e52.png)

**Comment by Skeeve2** [comment]
It is still fundamentally the same design as the last stations, as it only takes two doors to access the armory. However, it is actually harder to get into from the previous iteration, as there is only one access and the warden has a clear view of it. Adding more doors would not help the crowbar situation, but even then, there are no crowbars available to prisoners by default. If the person has an RCD, there is not much that can be done anyways. 

All of the above problems can be fixed with a vigilant warden; unfortunately, it's not possible on a low population for security to watch it. The problem can't be solved by adding more doors or making it more visible, as we don't want to make it impossible to break into the armory. It's up to the crew, AI or security to do regular checks on it.

I can't think of a situation where adding more doors or moving the armory to anywhere in security would solve the problem. A warden is a vital part of security now, and always has been for the armory. If security was really scared of that happening, they could add barricades. It's really up to them, there's not much we can do mapping wise to help solve the problem other then moving the armory to an easily visible spot, but that is a balance issue.

**Comment by Psyentific** [comment]
Most Boxstations have the armory buried deep in Security. Right now the Brig/Warden/Armory layout is very good and a Warden can keep an eye on everything in his office. The only real problem is that the armory is exactly the same unpartitioned hallway as the brig cells. Like, if those shutters are opened you can run right out of the cells and grab a gun right off the racks. A pair of double doors right where the firelocks are would solve that handily, partitioning it into a High Security hallway and a Prison hallway.

**Comment by Skeeve2** [comment]
It seems like a human error issue. Adding more doors would debatably solve a very minor problem. It's not really worthy of adding at the moment. I would only consider it, if it became a problem. To my knowledge this is all hypothetical right now.
