### ISSUE TITLE
Server crashes at initialization stage

### ISSUE THREAD

**Issue by martinlyra** [UristMcStation/UristMcStation#703]
#### Description of issue
Server crashes at the initialization stage, often leaving behind no logs or additional information around the event. There are two different flavours;
* Crashes at map init - narrowed down to cave and ore generation
* Crashes soon as a gamemode vote had started

#### Difference between expected and actual behavior
No crashes

#### Steps to reproduce 
The crashes are difficult to reproduce in the normal environment since they occur irregularly (fancy way to say random). Forcing the server to spawn more than two exoplanets reduces this irregularity and gives more instances of crashing at map generation. Disabling random exo-planets altogether dramatically reduces the crashes to zero.

#### Specific information for locating
The crashes occur without any other additional information. To recite the description;
* Map generation
* After gamemode voting's start

#### Length of time in which bug has been known to occur
Unknown length, but it is widely known by developers and players.

#### Client version, Server revision & Game ID
Only server revision applicable: e904f40589d89d4cbb562b2affccf38a374060d2

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by Glloyd** [comment]
@Naxodile fixed the gamemode crash in #705 

The other crash happens during Object Initialization.

**Comment by Glloyd** [comment]
This has been happening since at least March. It is unrelated to templates, and is related to something going wrong during atom initialization. 

It's not due to a specific issue with any awaymap, I sorted through a month's worth of logs, and couldn't find any correlation between crashing and specific awaymaps. Mining - Planetoid and orbital station seemed to show up more often than not, but the crashes still happened on rounds where neither were present. I don't know if @Naxodile has any ideas, but I am officially stumped.

**Comment by Glloyd** [comment]
keeping this open for now, just in case
